package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.ContractBean;
import com.lanou.entity.Contract;
import com.lanou.entity.ContractHis;
@MapperScan
public interface ContractHisMapper {
	
	
	
	/**
	 * 查询全部购销合同历史
	 * @return
	 */
	List<ContractBean> selectAll();
	
	/**
	 * 根据工厂名称查询合同信息
	 * @param factory_name
	 * @return
	 */
	List<ContractHis> selectContractHisByFactoryName(String factory_name);
	
	/**
	 * 查询总金额最的合同信息
	 * @return
	 */
	ContractHis selectContractHisByTotalMoney();
	
	/**最近3-6月
	 * ContractHis 
	 * @return
	 */
	List<ContractHis> selectContractHisByMonth(@Param("delivery_period")String delivery_period );
	
	/**
	 * 根据年份查询合同列表

	 * @param year
	 * @return
	 */
	List<ContractHis> selectByYear(@Param("year")String year);
	
	
	//###########################################################################
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String CONTRACT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(ContractHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    ContractHis selectByPrimaryKey(String CONTRACT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(ContractHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(ContractHis record);
}