package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.ContractProduct;
import com.lanou.entity.ContractProductHis;
@MapperScan
public interface ContractProductHisMapper {
	
	
	/**
	 * 根据合同历史id查询历史货物
	 * @param ContractHisId
	 * @return
	 */
	List<ContractProductHis> selectContractProductHisByContractHisId(String CONTRACT_ID);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String CONTRACT_PRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(ContractProductHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(ContractProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    ContractProductHis selectByPrimaryKey(String CONTRACT_PRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(ContractProductHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(ContractProductHis record);
}