package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.ExtCproduct;
import com.lanou.entity.ExtCproductHis;
@MapperScan
public interface ExtCproductHisMapper {
	
	
	/**
	 * 根据货物id查询所有附件
	 * @return
	 */
	List<ExtCproductHis> selectExtCproductHisByContractProductId(String CONTRACT_PRODUCT_ID);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String EXT_CPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(ExtCproductHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(ExtCproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    ExtCproductHis selectByPrimaryKey(String EXT_CPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(ExtCproductHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(ExtCproductHis record);
}