package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.ExtEproduct;
@MapperScan
public interface ExtEproductMapper {
	
	/**
	 * 根据报运货物id查询报运附件
	 * @param EXPORT_PRODUCT_ID
	 * @return
	 */
	List<ExtEproduct> selectExtEproductByEXPORT_PRODUCT_ID(String EXPORT_PRODUCT_ID);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String EXT_EPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    ExtEproduct selectByPrimaryKey(String EXT_EPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(ExtEproduct record);
}