package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.PackingList;
@MapperScan
public interface PackingListMapper {
	
	
	
	/**
	 * 查询所有
	 * @return
	 */
	List<PackingList> selectAll();
	
	
	//****************************************************************************
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACKING_LIST_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String PACKING_LIST_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACKING_LIST_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(PackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACKING_LIST_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(PackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACKING_LIST_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    PackingList selectByPrimaryKey(String PACKING_LIST_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACKING_LIST_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(PackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACKING_LIST_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(PackingList record);
}